USE MP
GO

INSERT INTO Pais.TB_Municipios(id_departamento, municipio_nombre)
    VALUES
	  -- Petén
    (1, 'Dolores'),
    (1, 'El Chal'),
    (1, 'Ciudad Flores'),
    (1, 'La Libertad'),
    (1, 'Las Cruces'),
    (1, 'Melchor de Mencos'),
    (1, 'Poptún'),
    (1, 'San Andrés'),
    (1, 'San Benito'),
    (1, 'San Francisco'),
    (1, 'San José'),
    (1, 'San Luis'),
    (1, 'Santa Ana'),
    (1, 'Sayaxché'),

	-- Guatemala

	(2, 'Amatitlán'),
    (2, 'Chinautla'),
    (2, 'Chuarrancho'),
    (2, 'Guatemala'),
    (2, 'Fraijanes'),
    (2, 'Mixco'),
    (2, 'Palencia'),
    (2, 'San José del Golfo'),
    (2, 'San José Pinula'),
    (2, 'San Juan Sacatepéquez'),
    (2, 'San Miguel Petapa'),
    (2, 'San Pedro AyaPaisuc'),
    (2, 'San Pedro Sacatepéquez'),
    (2, 'San Raymundo'),
    (2, 'Santa Catarina Pinula'),
    (2, 'Villa Canales'),
    (2, 'Villa Nueva'),

	-- Jutiapa
    (3, 'Agua Blanca'),
    (3, 'Asunción Mita'),
    (3, 'AtescatePaisa'),
    (3, 'Comapa'),
    (3, 'Conguaco'),
    (3, 'El Adelanto'),
    (3, 'El Progreso'),
    (3, 'Jalpatagua'),
    (3, 'Jerez'),
    (3, 'Jutiapa'),
    (3, 'Moyuta'),
    (3, 'Pasaco'),
    (3, 'Quesada'),
    (3, 'San José AcatePaisa'),
    (3, 'Santa Catarina Mita'),
    (3, 'Yupiltepeque'),
    (3, 'Zapotitlán'),


      -- Alta Verapaz
    (4, 'Chahal'),
    (4, 'Chisec'),
    (4, 'Cobán'),
    (4, 'Fray Bartolomé de las Casas'),
    (4, 'La Tinta'),
    (4, 'Lanquín'),
    (4, 'Panzós'),
    (4, 'Raxruhá'),
    (4, 'San Cristóbal Verapaz'),
    (4, 'San Juan Chamelco'),
    (4, 'San Pedro Carchá'),
    (4, 'Santa Cruz Verapaz'),
    (4, 'Santa María Cahabón'),
    (4, 'Senahú'),
    (4, 'Tamahú'),
    (4, 'Tactic'),
    (4, 'Tucurú'),


	-- Quiché
    (5, 'Canillá'),
    (5, 'Chajul'),
    (5, 'Chicamán'),
    (5, 'Chiché'),
    (5, 'Chichicastenango'),
    (5, 'Chinique'),
    (5, 'Cunén'),
    (5, 'Ixcán Playa Grande'),
    (5, 'Joyabaj'),
    (5, 'Nebaj'),
    (5, 'Pachalum'),
    (5, 'Patzité'),
    (5, 'Sacapulas'),
    (5, 'San Andrés Sajcabajá'),
    (5, 'San Antonio Ilotenango'),
    (5, 'San Bartolomé Jocotenango'),
    (5, 'San Juan Cotzal'),
    (5, 'San Pedro Jocopilas'),
    (5, 'Santa Cruz del Quiché'),
    (5, 'Uspantán'),
    (5, 'Zacualpa'),

	 -- Huehuetenango
    (6,'Aguacatán'),
    (6,'Chiantla'),
    (6,'Colotenango'),
    (6,'Concepción Huista'),
    (6,'Cuilco'),
    (6,'Huehuetenango'),
    (6,'Jacaltenango'),
    (6,'La Democracia'),
    (6,'La Libertad'),
    (6,'Malacatancito'),
    (6,'Nentón'),
    (6,'San Antonio Huista'),
    (6,'San Gaspar Ixchil'),
    (6,'San Ildefonso Ixtahuacán'),
    (6,'San Juan Atitán'),
    (6,'San Juan Ixcoy'),
    (6,'San Mateo Ixtatán'),
    (6,'San Miguel Acatán'),
    (6,'San Pedro Nécta'),
    (6,'San Pedro Soloma'),
    (6,'San Rafael La Independencia'),
    (6,'San Rafael Pétzal'),
    (6,'San Sebastián Coatán'),
    (6,'San Sebastián Huehuetenango'),
    (6,'Santa Ana Huista'),
    (6,'Santa Bárbara'),
    (6,'Santa Cruz Barillas'),
    (6,'Santa Eulalia'),
    (6,'Santiago Chimaltenango'),
    (6,'Tectitán'),
    (6,'Todos Santos Cuchumatán'),
    (6,'Unión Cantinil'),

	 -- Escuintla
    (7, 'Escuintla'),
    (7, 'Guanagazapa'),
    (7, 'Iztapa'),
    (7, 'La Democracia'),
    (7, 'La Gomera'),
    (7, 'Masagua'),
    (7, 'Nueva Concepción'),
    (7, 'Palín'),
    (7, 'San José'),
    (7, 'San Vicente Pacaya'),
    (7, 'Santa Lucía Cotzumalguapa'),
    (7, 'Siquinalá'),
    (7, 'Tiquisate'),

	-- San Marcos
    (8, 'Ayutla'),
    (8, 'Catarina'),
    (8, 'Comitancillo'),
    (8, 'Concepción Tutuapa'),
    (8, 'El Quetzal'),
    (8, 'El Tumbador'),
    (8, 'Esquipulas Palo Gordo'),
    (8, 'Ixchiguán'),
    (8, 'La Blanca'),
    (8, 'La Reforma'),
    (8, 'Malacatán'),
    (8, 'Nuevo Progreso'),
    (8, 'Ocós'),
    (8, 'Pajapita'),
    (8, 'Río Blanco'),
    (8, 'San Antonio Sacatepéquez'),
    (8, 'San Cristóbal Cucho'),
    (8, 'San José El Rodeo'),
    (8, 'San José Ojetenam'),
    (8, 'San Lorenzo'),
    (8, 'San Marcos'),
    (8, 'San Miguel Ixtahuacán'),
    (8, 'San Pablo'),
    (8, 'San Pedro Sacatepéquez'),
    (8, 'San Rafael Pie de la Cuesta'),
    (8, 'Sibinal'),
    (8, 'Sipacapa'),
    (8, 'Tacaná'),
    (8, 'Tajumulco'),
    (8, 'Tejutla'),


	 -- Baja Verapaz
    (9,'Cubulco'),
    (9,'Granados'),
    (9,'Purulhá'),
    (9,'Rabinal'),
    (9,'Salamá'),
    (9,'San Jerónimo'),
    (9,'San Miguel Chicaj'),
    (9,'Santa Cruz el Chol'),


	 -- Santa Rosa
    (10, 'Barberena'),
    (10, 'Casillas'),
    (10, 'Chiquimulilla'),
    (10, 'Cuilapa'),
    (10, 'Guazacapán'),
    (10, 'Nueva Santa Rosa'),
    (10, 'Oratorio'),
    (10, 'Pueblo Nuevo Viñas'),
    (10, 'San Juan Tecuaco'),
    (10, 'San Rafael las Flores'),
    (10, 'Santa Cruz Naranjo'),
    (10, 'Santa María Ixhuatán'),
    (10, 'Santa Rosa de Lima'),
    (10, 'Taxisco'),


	-- Zacapa
    (11, 'Cabañas'),
    (11, 'Estanzuela'),
    (11, 'Gualán'),
    (11, 'Huité'),
    (11, 'La Unión'),
    (11, 'Río Hondo'),
    (11, 'San Diego'),
    (11, 'San Jorge'),
    (11, 'Teculután'),
    (11, 'Usumatlán'),
    (11, 'Zacapa'),


	
	-- Suchitepéquez
    (12, 'Chicacao'),
    (12, 'Cuyotenango'),
    (12, 'Mazatenango'),
    (12, 'Patulul'),
    (12, 'Pueblo Nuevo'),
    (12, 'Río Bravo'),
    (12, 'Samayac'),
    (12, 'San Antonio Suchitepéquez'),
    (12, 'San Bernardino'),
    (12, 'San Francisco Zapotitlán'),
    (12, 'San Gabriel'),
    (12, 'San José El Idolo'),
    (12, 'San José La Maquina'),
    (12, 'San Juan Bautista'),
    (12, 'San Lorenzo'),
    (12, 'San Miguel Panán'),
    (12, 'San Pablo Jocopilas'),
    (12, 'Santa Bárbara'),
    (12, 'Santo Domingo Suchitepéquez'),
    (12, 'Santo Tomás La Unión'),
    (12, 'Zunilito'),

	 -- Chiquimula
    (13, 'Camotán'),
    (13, 'Chiquimula'),
    (13, 'Concepción Las Minas'),
    (13, 'Esquipulas'),
    (13, 'Ipala'),
    (13, 'Jocotán'),
    (13, 'Olopa'),
    (13, 'Quezaltepeque'),
    (13, 'San Jacinto'),
    (13, 'San José la Arada'),
    (13, 'San Juan Ermita'),


	  -- Jalapa
    (14, 'Jalapa'),
    (14, 'Mataquescuintla'),
    (14, 'Monjas'),
    (14, 'San Carlos Alzatate'),
    (14, 'San Luis Jilotepeque'),
    (14, 'San Manuel Chaparrón'),
    (14, 'San Pedro Pinula'),
	   
	  
	 -- Chimaltenango
    (15, 'Acatenango'),
    (15, 'Chimaltenango'),
    (15, 'El Tejar'),
    (15, 'Parramos'),
    (15, 'Patzicía'),
    (15, 'Patzún'),
    (15, 'Pochuta'),
    (15, 'San Andrés Itzapa'),
    (15, 'San José Poaquíl'),
    (15, 'San Juan Comalapa'),
    (15, 'San Martín Jilotepeque'),
    (15, 'Santa Apolonia'),
    (15, 'Santa Cruz Balanyá'),
    (15, 'Tecpán'),
    (15, 'Yepocapa'),
    (15, 'Zaragoza'),

	-- Quetzaltenango
    (16, 'Almolonga'),
    (16, 'Cabricán'),
    (16, 'Cajolá'),
    (16, 'Cantel'),
    (16, 'Coatepeque'),
    (16, 'Colomba Costa Cuca'),
    (16, 'Concepción Chiquirichapa'),
    (16, 'El Palmar'),
    (16, 'Flores Costa Cuca'),
    (16, 'Génova'),
    (16, 'Huitán'),
    (16, 'La Esperanza'),
    (16, 'Olintepeque'),
    (16, 'Palestina de Los Altos'),
    (16, 'Quetzaltenango'),
    (16, 'Salcajá'),
    (16, 'San Carlos Sija'),
    (16, 'San Francisco La Unión'),
    (16, 'San Juan Ostuncalco'),
    (16, 'San Martín Sacatepéquez'),
    (16, 'San Mateo'),
    (16, 'San Miguel Sigüilá'),
    (16, 'Sibilia'),
    (16, 'Zunil'),
	
	  -- El Progreso
    (17, 'El Jícaro'),
    (17, 'Guastatoya'),
    (17, 'Morazán'),
    (17, 'San Agustín Acasaguastlán'),
    (17, 'San Antonio La Paz'),
    (17, 'San Cristóbal Acasaguastlán'),
    (17, 'Sanarate'),
    (17, 'Sansare'),


	-- Retalhuleu
    (18, 'ChaPaiserico'),
    (18, 'El Asintal'),
    (18, 'Nuevo San Carlos'),
    (18, 'Retalhuleu'),
    (18, 'San Andrés Villa Seca'),
    (18, 'San Felipe Reu'),
    (18, 'San Martín Zapotitlán'),
    (18, 'San Sebastián'),
    (18, 'Santa Cruz Muluá'),

	-- Sololá
    (19, 'Concepción'),
    (19, 'Nahualá'),
    (19, 'Panajachel'),
    (19, 'San Andrés Semetabaj'),
    (19, 'San Antonio Palopó'),
    (19, 'San José Chacayá'),
    (19, 'San Juan La Laguna'),
    (19, 'San Lucas Tolimán'),
    (19, 'San Marcos La Laguna'),
    (19, 'San Pablo La Laguna'),
    (19, 'San Pedro La Laguna'),
    (19, 'Santa Catarina Ixtahuacán'),
    (19, 'Santa Catarina Palopó'),
    (19, 'Santa Clara La Laguna'),
    (19, 'Santa Cruz La Laguna'),
    (19, 'Santa Lucía Utatlán'),
    (19, 'Santa María Visitación'),
    (19, 'Santiago Atitlán'),
    (19, 'Sololá'),

	 -- Totonicapán
    (20, 'Momostenango'),
    (20, 'San Andrés Xecul'),
    (20, 'San Bartolo'),
    (20, 'San Cristóbal Totonicapán'),
    (20, 'San Francisco El Alto'),
    (20, 'Santa Lucía La Reforma'),
    (20, 'Santa María Chiquimula'),
    (20, 'Totonicapán'),


	 -- Sacatepéquez
    (21, 'Alotenango'),
    (21, 'Ciudad Vieja'),
    (21, 'Jocotenango'),
    (21, 'Antigua Guatemala'),
    (21, 'Magdalena Milpas Altas'),
    (21, 'Pastores'),
    (21, 'San Antonio Aguas Calientes'),
    (21, 'San Bartolomé Milpas Altas'),
    (21, 'San Lucas Sacatepéquez'),
    (21, 'San Miguel Dueñas'),
    (21, 'Santa Catarina Barahona'),
    (21, 'Santa Lucía Milpas Altas'),
    (21, 'Santa María de Jesús'),
    (21, 'Santiago Sacatepéquez'),
    (21, 'Santo Domingo Xenacoj'),
    (21, 'SuPaisango'),

	 -- Izabal
    (22, 'El Estor'),
    (22, 'Livingston'),
    (22, 'Los Amates'),
    (22, 'Morales'),
    (22, 'Puerto Barrios');
